### ISSUE TITLE
Create wireframe for user-facing features (Sat.)

### ISSUE THREAD

**Issue by DanielEFrampton** [DanielEFrampton/dev.to#11]

**Comment by nwgambee** [comment]
![IMG_0540](https://user-images.githubusercontent.com/53379017/77328206-d8440800-6ce1-11ea-8fb2-0adadf0d6ff8.jpg)
![IMG_0541](https://user-images.githubusercontent.com/53379017/77328217-daa66200-6ce1-11ea-898a-80d84505608e.jpg)
![IMG_0542](https://user-images.githubusercontent.com/53379017/77328223-dbd78f00-6ce1-11ea-9a72-750065526951.jpg)
![IMG_0543](https://user-images.githubusercontent.com/53379017/77328229-dd08bc00-6ce1-11ea-8837-b5bc49568a6a.jpg)
